# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc8a62ac95b90c49e93a9e535ad522dec554f0dd5d371df39cde4802a457f8f8d026e8884776aa7b325e0debc127f3d3c721fdbda2fda98d27a95a4ff3aa59fd

test:
  secret_key_base: a1822a44a44cd31be02132d33b5e195347ab5e8bbad39cad68a78ddd2c150bf42286adaf9b8d2ca85516792cfb8ca79a23c5359a759d4b694f03fad83b7dbc70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
